
extends Node

var map = {	"Up":"CHAR_UP", 
			"Down":"CHAR_DOWN", 
			"Left":"CHAR_LEFT", 
			"Right":"CHAR_RIGHT", 
			"Shift":"CHAR_SHIFT", 
			"Control":"CHAR_CTRL", 
			"Alt":"CHAR_ALT", 
			"Tab":"CHAR_TAB",
			"Escape":"CHAR_ESC",
			"BackSpace":"CHAR_BACKSPACE",
			"Space":"CHAR_SPACE",
			"Return":"CHAR_RETURN",
			"Print":"CHAR_PRINT",
			"Pause":"CHAR_PAUSE",
			"Insert":"CHAR_INS",
			"Delete":"CHAR_DEL",
			"Home":"CHAR_HOME",
			"End":"CHAR_END",
			"PageUp":"CHAR_PAGEUP",
			"PageDown":"CHAR_PAGEDOWN",
			"Meta":"CHAR_META",
			"Kp Enter":"CHAR_ENTER",
			"Enter":"CHAR_ENTER",
			"CapsLock":"CHAR_CAPS",
			"NumLock":"CHAR_NUM",
			"ScrollLock":"CHAR_SCROLL",
			"F1":"CHAR_F1",
			"F2":"CHAR_F2",
			"F3":"CHAR_F3",
			"F4":"CHAR_F4",
			"F5":"CHAR_F5",
			"F6":"CHAR_F6",
			"F7":"CHAR_F7",
			"F8":"CHAR_F8",
			"F9":"CHAR_F9",
			"F10":"CHAR_F10",
			"F11":"CHAR_F11",
			"F12":"CHAR_F12",
			"F13":"CHAR_F13",
			"F14":"CHAR_F14",
			"F15":"CHAR_F15",
			"F16":"CHAR_F16",
			"Kp Multiply":"CHAR_*",
			"Kp Divide":"CHAR_/",
			"Kp Subtract":"CHAR_-",
			"Kp Period":"CHAR_.",
			"Kp Add":"CHAR_+",
			"Kp 0":"CHAR_0",
			"Kp 1":"CHAR_1",
			"Kp 2":"CHAR_2",
			"Kp 3":"CHAR_3",
			"Kp 4":"CHAR_4",
			"Kp 5":"CHAR_5",
			"Kp 6":"CHAR_6",
			"Kp 7":"CHAR_7",
			"Kp 8":"CHAR_8",
			"Kp 9":"CHAR_9",
			"Plus":"CHAR_+",
			"Comma":"CHAR_,",
			"Minus":"CHAR_-",
			"Period":"CHAR_.",
			"Slash":"CHAR_/",
			"0":"CHAR_0",
			"1":"CHAR_1",
			"2":"CHAR_2",
			"3":"CHAR_3",
			"4":"CHAR_4",
			"5":"CHAR_5",
			"6":"CHAR_6",
			"7":"CHAR_7",
			"8":"CHAR_8",
			"9":"CHAR_9",
			"Semicolon":"CHAR_;",
			"Less":"CHAR_<",
			"Equal":"CHAR_=",
			"Apostrophe":"CHAR_'",
			"Asterisk":"CHAR_*",
			"QuoteLeft":"CHAR_`",
			"Acute":"CHAR_´",
			"A":"CHAR_A",
			"B":"CHAR_B",
			"C":"CHAR_C",
			"D":"CHAR_D",
			"E":"CHAR_E",
			"F":"CHAR_F",
			"G":"CHAR_G",
			"H":"CHAR_H",
			"I":"CHAR_I",
			"J":"CHAR_J",
			"K":"CHAR_K",
			"L":"CHAR_L",
			"M":"CHAR_M",
			"N":"CHAR_N",
			"O":"CHAR_O",
			"P":"CHAR_P",
			"Q":"CHAR_Q",
			"R":"CHAR_R",
			"S":"CHAR_S",
			"T":"CHAR_T",
			"U":"CHAR_U",
			"V":"CHAR_V",
			"W":"CHAR_W",
			"X":"CHAR_X",
			"Y":"CHAR_Y",
			"Z":"CHAR_Z",
			"BracketLeft":"CHAR_[",
			"BraceLeft":"CHAR_[",
			"BackSlash":"CHAR_\\",
			"BracketRight":"CHAR_]",
			"BraceRight":"CHAR_]",
			"AsciiCircum":"CHAR_^",
			"Adiaeresis":"CHAR_Ä",
			"Odiaeresis":"CHAR_Ö",
			"Udiaeresis":"CHAR_Ü",
			"NumberSign":"CHAR_#",
			"Ssharp":"CHAR_ß"}
var inputs = ["ui_up", "ui_down", "ui_left", "ui_right", "ui_jump", "ui_attack", "ui_magic", "ui_blood", "ui_spell_prev", "ui_spell_next", "ui_pause", "ui_select"]
var keys = {}

func _init():
	update_keys()

func update_keys():
	for i in inputs:
		update_key(i)

func update_key(key):
	for i in InputMap.get_action_list(key):
		if (i.type == InputEvent.KEY):
			keys[key] = i.scancode

func map_action(action):
	return map_key(OS.get_scancode_string(keys[action]))

func map_key(input):
	if (map.has(input)):
		return tr(map[input])
	return input